[package]
name = "porter-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4_flex = { version = "0.11", default-features = false, features = ["safe-encode", "safe-decode"] }
num_cpus = { version = "1.16" }
sanitize-filename = { version = "0.5", default-features = false }
